lib/crisp_web/router.ex
defmodule CrispWeb.Router do
  use CrispWeb, :router

  import CrispWeb.Authentication
  import CrispWeb.Onboarding

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_employee
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Non-authenticated routes
  scope "/", CrispWeb do
    pipe_through [:browser, :redirect_authenticated_employee]

    get "/tunnistaudu", StrongAuthenticationController, :login
    get "/liity", StrongAuthenticationController, :registration
    get "/salasana/uusi", StrongAuthenticationController, :reset_password
    post "/tunnistaudu", StrongAuthenticationController, :create
    get "/callback", StrongAuthenticationController, :callback

    get "/kirjaudu", SessionController, :new
    post "/kirjaudu", SessionController, :create
  end

  # Public
  scope "/", CrispWeb do
    pipe_through [:browser]

    get "/kayttoonotto/vahvistus/:token", EmailConfirmationController, :confirm
  end

  scope "/kayttoonotto", CrispWeb do
    pipe_through [
      :browser,
      :require_authenticated_employee,
      :check_onboarding_state,
      :redirect_onboarded_employees
    ]

    get "/vahvistus", EmailConfirmationController, :show

    # /kayttoonotto/tunnukset
    get "/tiedot", PersonalInformationController, :new
    post "/tiedot", PersonalInformationController, :create
  end

  # allows employees to log out even if they have not
  # completed onboarding
  scope "/", CrispWeb do
    pipe_through [:browser, :require_authenticated_employee]

    delete "/kirjaudu-ulos", SessionController, :delete
  end

  # Authenticated routes
  scope "/", CrispWeb do
    pipe_through [:browser, :require_authenticated_employee, :check_onboarding_state]

    # Onboarding, luo tunnarit
    get "/tunnukset", CredentialsController, :new
    post "/tunnukset", CredentialsController, :create

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", CrispWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: CrispWeb.Telemetry
    end
  end
end

lib/crisp_web/controllers/personal_information_controller.ex
defmodule CrispWeb.PersonalInformationController do
  use CrispWeb, :controller

  alias Crisp.Accounts

  def new(conn, _params) do
    employee = conn.assigns.current_employee
    changeset = Accounts.change_employee_personal_information(employee)
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"employee" => params}) do
    employee = conn.assigns.current_employee

    case Accounts.update_employee_personal_information(employee, params) do
      {:ok, _employee} -> conn |> put_flash(:info, 'Onboarding valmis.') |> redirect(to: "/")
      {:error, changeset} -> render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/crisp_web/views/personal_information_view.ex
defmodule CrispWeb.PersonalInformationView do
  use CrispWeb, :view
end

lib/crisp_web/templates/personal_information/new.html.eex
<%= form_for @changeset, Routes.personal_information_path(@conn, :create), [method: :post], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :firstname %>
  <%= text_input f, :firstname, required: true %>
  <%= error_tag f, :firstname %>

  <%= label f, :lastname %>
  <%= text_input f, :lastname, required: true %>
  <%= error_tag f, :lastname %>

  <%= label f, :phonenumber %>
  <%= text_input f, :phonenumber, required: true %>
  <%= error_tag f, :phonenumber %>

  <%= label f, :nationality %>
  <%= text_input f, :nationality, required: true %>
  <%= error_tag f, :nationality %>

  <%= label f, :address %>
  <%= text_input f, :address, required: true %>
  <%= error_tag f, :address %>

  <%= label f, :city %>
  <%= text_input f, :city, required: true %>
  <%= error_tag f, :city %>

  <%= label f, :zip %>
  <%= text_input f, :zip, required: true %>
  <%= error_tag f, :zip %>

  <%= label f, :iban %>
  <%= text_input f, :iban, required: true %>
  <%= error_tag f, :iban %>

  <%= label f, :business_description %>
  <%= text_input f, :business_description, required: true %>
  <%= error_tag f, :business_description %>

  <%= label f, :business_scope %>
  <%= text_input f, :business_scope, required: true %>
  <%= error_tag f, :business_scope %>

  <div>
    <%= submit "Submit" %>
  </div>
<% end %>

lib/crisp_web/templates/personal_information/ok.html.eex
<p>Jee! hyvin päivitetty</p>